import type { Metadata } from "next";
import { BaseLayout } from "@/fsd/app/layouts/BaseLayout";
import { ReactNode } from "react";
import { Header } from "@/fsd/widgets/header/index";
import "./globals.css";

export const metadata: Metadata = {
  title: "Artspire",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BaseLayout>
          <Header />
          <section className="main__section">{children}</section>
        </BaseLayout>
      </body>
    </html>
  );
}
