import type { Metadata } from "next";
import { BaseLayout } from "@/fsd/app/layouts/BaseLayout";
import { ReactNode } from "react";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Artspire",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BaseLayout>
          <section className="main__section">{children}</section>
        </BaseLayout>
      </body>
    </html>
  );
}
